# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isobres', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobre',
            old_name='data',
            new_name='date',
        ),
    ]
